# Generated by Django 3.1.7 on 2021-04-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='media/uploads/profile_pictures/default.png', null=True, upload_to='uploads/profile_pictures'),
        ),
    ]
