# Generated by Django 3.1.7 on 2021-04-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20210401_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='picturem',
        ),
    ]
