# Generated by Django 3.1.7 on 2021-04-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20210401_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picturem',
            new_name='picture',
        ),
    ]
