# Generated by Django 3.1.7 on 2021-04-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20210401_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='media/uploads/profile_pictures/default.png', upload_to='uploads/profile_pictures'),
        ),
    ]
