# Generated by Django 3.1.7 on 2021-04-12 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0009_auto_20210408_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='loves',
            field=models.ManyToManyField(blank=True, related_name='loves', to=settings.AUTH_USER_MODEL),
        ),
    ]
